### ISSUE TITLE
👋🏻

### ISSUE THREAD

**Issue by prateekbh** [devalexandre/preact-mui-components#1]
Hi!
I am maintainer of a similar project <https://github.com/prateekbh/preact-material-components/>

Lately I have not been able to maintain the repo due to commitments to other projects.
I would love to sync on your approach here and may be contribute some stuff as I am pretty passionate towards the cause but does not have all the bandwidth for it.

Keen to hear from you :)

**Comment by devalexandre** [comment]
very cool, I saw your project and followed for a while how I fell in love with preact I decided to make the componenets and also a template that I hope will one day become official

https://github.com/devalexandre/preact-mui

if you have any tips, it would be really cool

**Comment by prateekbh** [comment]
I do have a question. Have you decided on any implementation details? 

- are you re-using some of the work from google material components web?
- how are you planning on bundling your components?
- do you have any testing strategy in mind? I can help you on this front if you want(percy/codesandbox CI)

**Comment by devalexandre** [comment]
I'm creating some components, reusing the material's user interface components.

Referring to tests I have nothing in mind to implement, but seriously interesting to do the tests

**Comment by prateekbh** [comment]
check this out: https://percy.io/
just simple visual comparison thing. Pretty easy than the others found in the same space

**Comment by devalexandre** [comment]
I will check, this interface test part is something I have little knowledge, I will see how it works to be able to create something solid

**Comment by devalexandre** [comment]
Have some doc how use percy with preact?
